Jobbply- Final Project/Jobbply- Final Project/Models/ClientSlider.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Jobbply__Final_Project.Models
{
    public class ClientSlider
    {
        public int Id { get; set; }

        public string Image { get; set; }


        [NotMapped]
        //[Required]
        public IFormFile Photo { get; set; }


        //[Required]
        //[MaxLength(100, ErrorMessage = "100-den cox olmamalidir")]
        public string Desc { get; set; }


        //[Required(ErrorMessage = "don't empty")]
        //[MaxLength(15, ErrorMessage = "15-den cox olmamalidir")]
        public string Name { get; set; }


       // [Required(ErrorMessage = "don't empty")]
        //[MaxLength(20, ErrorMessage = "20-den cox olmamalidir")]
        public string Position { get; set; }
    }
}

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Controllers/ClientSliderController.cs
using Jobbply__Final_Project.DAL;
using Jobbply__Final_Project.Helpers;
using Jobbply__Final_Project.Models;
using Jobbply__Final_Project.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Jobbply__Final_Project.Areas.AdminF.Controllers
{
    [Area("AdminF")]
    public class ClientSliderController : Controller
    {
        private AppDbContext _context;
        private IWebHostEnvironment _env;
        public ClientSliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index(int take = 5, int pageSize = 1)
        {
            List<ClientSlider> clientSliders = _context.ClientSliders.Skip((pageSize - 1) * take)
                .Take(take)
                .ToList();

            Pagination<ClientSlider> pagination = new Pagination<ClientSlider>(
               ReturnPageCount(take),
               pageSize,
               clientSliders
               );
            return View(pagination);
        }
        private int ReturnPageCount(int take)
        {
            int sliderCount = _context.ClientSliders.Count();
            return (int)Math.Ceiling(((decimal)sliderCount / take));
        }


        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return NotFound();

            ClientSlider dbClientSlider = await _context.ClientSliders.FindAsync(id);
            if (dbClientSlider == null) return NotFound();
            return View(dbClientSlider);
        }

        
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            ClientSlider dbClientSlider = await _context.ClientSliders.FindAsync(id);
            if (dbClientSlider == null) return NotFound();

            Helper.DeleteFile(_env, "assets","image","home", dbClientSlider.Image);
            _context.ClientSliders.Remove(dbClientSlider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientSlider clientSlider)
        {
            if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                return View();
            }

            if (!clientSlider.Photo.ContentType.Contains("image"))
            {
                ModelState.AddModelError("Photo", "Accept Only image");
                return View();
            }

            if (clientSlider.Photo.Length/1024>1024)
            {
                ModelState.AddModelError("Photo", "1mb-dan yuxari ola bilmez");
                return View();
            }
            // string path = @"C:\Users\nargi\Desktop\Jobbply- Final Project\Jobbply- Final Project\wwwroot\assets\image\home\";
           
            string path = _env.WebRootPath;
            string fileName = Guid.NewGuid().ToString() + clientSlider.Photo.FileName;
            string result = Path.Combine(path, "assets", "image", "home", fileName);

            using (FileStream stream=new FileStream (result,FileMode.Create))
            {
                await clientSlider.Photo.CopyToAsync(stream);
            };
            ClientSlider newClientSlider = new ClientSlider();
            newClientSlider.Image = fileName;
            newClientSlider.Desc = clientSlider.Desc;
            newClientSlider.Name = clientSlider.Name;
            newClientSlider.Position = clientSlider.Position;
            await _context.ClientSliders.AddAsync(newClientSlider);
            await _context.SaveChangesAsync();

            //bool isExistName = _context.ClientSliders.Any(c => c.Name.ToLower() == clientSlider.Name.ToLower());
            //if (isExistName)
            //{
            //    ModelState.AddModelError("Name", "Eyni adli Client movcuddur");
            //    return View();
            //}

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return NotFound();

            ClientSlider dbClientSlider = await _context.ClientSliders.FindAsync(id);
            if (dbClientSlider == null) return NotFound();
            return View(dbClientSlider);
        }


        [HttpPost]
        public async Task<IActionResult> Update(int? id, ClientSlider clientSlider)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            ClientSlider dbClientSlider = await _context.ClientSliders.FindAsync(id);

            ClientSlider existNameClientSlider = _context.ClientSliders.FirstOrDefault(c => c.Name.ToLower() == clientSlider.Name.ToLower());

            if (existNameClientSlider != null)
            {
                if (dbClientSlider != existNameClientSlider)
                {
                    ModelState.AddModelError("Name", "Title already exist");
                }
            }
            string path = _env.WebRootPath;
            string fileName = Guid.NewGuid().ToString() + clientSlider.Photo.FileName;
            string result = Path.Combine(path, "assets", "image", "home", fileName);

            using (FileStream stream = new FileStream(result, FileMode.Create))
            {
                await clientSlider.Photo.CopyToAsync(stream);
            };

            if (dbClientSlider == null) return NotFound();
            dbClientSlider.Image = fileName;
            dbClientSlider.Desc = dbClientSlider.Desc;
            dbClientSlider.Name = dbClientSlider.Name;
            dbClientSlider.Position = dbClientSlider.Position;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/ClientSlider/Create.cshtml
@model ClientSlider
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group" >
                      <label asp-for="Photo"></label>
                      <input asp-for="Photo" class="form-control"  placeholder="Photo" accept="image/*">
                      <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                      <label asp-for="Desc">Description</label>
                      <input asp-for="Desc" class="form-control" placeholder="Description">
                      <span asp-validation-for="Desc" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="Name">Name</label>
                      <input asp-for="Name" class="form-control" placeholder="Name">
                      <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="Position">Position</label>
                      <input asp-for="Position" class="form-control" placeholder="Position">
                      <span asp-validation-for="Position" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Create</button>
                  </form>
    </div>
</div>

@section Scripts{
    <partial name="_Validation"/>
    }

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/ClientSlider/Delete.cshtml
@model ClientSlider
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/ClientSlider/Detail.cshtml
@model ClientSlider
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<h1>@Model.Name</h1>
<h4>@Model.Position</h4>
<p>@Model.Desc</p>
<a class="btn btn-dark" asp-controller="clientslider" asp-action="index">Back</a>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/ClientSlider/Index.cshtml
@model Pagination<ClientSlider>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
     int count = (Model.CurrentPage - 1) * 5;
}

 <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">TopCategory Table</h4>
                  <a class="btn btn-success" asp-controller="ClientSlider" asp-action="Create" >Create</a>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Count</th>
                          <th>Image</th>
                          <th>Name</th>
                          <th>Position</th>
                          <th>Setting</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach (var item in Model.Items)
                       {
                                count++;
                         <tr>
                              <td>@count</td>
                              <td>
                                  <img src="~/assets/image/home/@item.Image" />
                              </td>
                              <td>@item.Name</td>
                              <td>@item.Position</td>
                              <td>
                                  <a class="btn btn-danger" asp-controller="ClientSlider" asp-action="delete" asp-route-id="@item.Id"><i class="mdi mdi-delete"></i></a>
                                  <a class="btn btn-primary" asp-controller="ClientSlider" asp-action="update" asp-route-id="@item.Id"><i class="mdi mdi-table-edit"></i></a>
                                  <a class="btn btn-info" asp-controller="ClientSlider" asp-action="detail" asp-route-id="@item.Id"><i class="mdi mdi-account-card-details"></i></a>
                              </td>
                        </tr>
                       }
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
 </div>

  <div class="row justify-content-center">
	<ul class="pagination pagination-lg">
		@for (var i = 1; i <= Model.PageCount; i++)
		{
			<li class="page-item @(Model.CurrentPage==i? "disabled" : "") ">
				<a class="page-link" 
				asp-area="adminf" 
				asp-controller="ClientSlider" 
				asp-action="index" 
				asp-route-pageSize="@i">@i</a>
			</li>
		}
	</ul>
</div>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/ClientSlider/Update.cshtml
@model ClientSlider
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group" >
                      <label asp-for="Photo"></label>
                      <input asp-for="Photo" class="form-control"  placeholder="Photo" accept="image/*">
                      <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                      <label asp-for="Desc">Description</label>
                      <input asp-for="Desc" class="form-control" placeholder="Description">
                      <span asp-validation-for="Desc" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="Name">Name</label>
                      <input asp-for="Name" class="form-control" placeholder="Name">
                      <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="Position">Position</label>
                      <input asp-for="Position" class="form-control" placeholder="Position">
                      <span asp-validation-for="Position" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Create</button>
                  </form>
    </div>
</div>

@section Scripts{
    <partial name="_Validation"/>
    }