Jobbply- Final Project/Jobbply- Final Project/Models/AvailableJob.cs
namespace Jobbply__Final_Project.Models
{
    public class AvailableJob
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string WorkTime { get; set; }
        public string Social { get; set; }
        public string Location { get; set; }
        public int Count { get; set; }
        public string Apply { get; set; }
    }
}

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Controllers/AvailableJobsController.cs
using Jobbply__Final_Project.DAL;
using Jobbply__Final_Project.Helpers;
using Jobbply__Final_Project.Models;
using Jobbply__Final_Project.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jobbply__Final_Project.Areas.AdminF.Controllers
{
    [Area("AdminF")]
    public class AvailableJobsController : Controller
    {
        private AppDbContext _context;
        private IWebHostEnvironment _env;
        public AvailableJobsController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index(int take = 5, int pageSize = 1)
        {
            List<AvailableJob> availableJobs = _context.AvailableJobs.Skip((pageSize - 1) * take)
                .Take(take)
                .ToList();


            Pagination<AvailableJob> pagination = new Pagination<AvailableJob>(
                ReturnPageCount(take),
                pageSize,
                availableJobs
                );
            return View(pagination);
        }
        private int ReturnPageCount(int take)
        {
            int availableJobCount = _context.AvailableJobs.Count();
            return (int)Math.Ceiling(((decimal)availableJobCount / take));
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return NotFound();

            AvailableJob dbAvailableJob = await _context.AvailableJobs.FindAsync(id);
            if (dbAvailableJob == null) return NotFound();
            return View(dbAvailableJob);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            AvailableJob dbAvailableJob = await _context.AvailableJobs.FindAsync(id);
            if (dbAvailableJob == null) return NotFound();

            //Helper.DeleteFile(_env, "assets", "image", "home", dbAvailableJob.Image);
            _context.AvailableJobs.Remove(dbAvailableJob);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AvailableJob availableJob)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            AvailableJob newAvailableJob = new AvailableJob();
            newAvailableJob.Title = availableJob.Title;
            newAvailableJob.WorkTime = availableJob.WorkTime;
            newAvailableJob.Social = availableJob.Social;
            newAvailableJob.Location = availableJob.Location;
            await _context.AvailableJobs.AddAsync(newAvailableJob);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return NotFound();

            AvailableJob dbAvailableJob = await _context.AvailableJobs.FindAsync(id);
            if (dbAvailableJob == null) return NotFound();
            return View(dbAvailableJob);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int? id, AvailableJob availableJob)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            AvailableJob dbAvailableJob = await _context.AvailableJobs.FindAsync(id);

            //AvailableJob existTitleJobInfo = _context.JobInfos.FirstOrDefault(j => j.Title.ToLower() == jobInfo.Title.ToLower());

            //if (existTitleJobInfo != null)
            //{
            //    if (dbJobinfo != existTitleJobInfo)
            //    {
            //        ModelState.AddModelError("Title", "Title already exist");
            //    }
            //}


            if (dbAvailableJob == null) return NotFound();

            dbAvailableJob.Title = availableJob.Title;
            dbAvailableJob.WorkTime = availableJob.WorkTime;
            dbAvailableJob.Social = availableJob.Social;
            dbAvailableJob.Location = availableJob.Location;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/AvailableJobs/Create.cshtml
@model AvailableJob
@{
	ViewData["Title"] = "Create";
	Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
	<div class="row">
		<form class="forms-sample" method="post" >
			<div class="form-group">
				<label asp-for="Title">Name</label>
				<input asp-for="Title" class="form-control" placeholder="Name">
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="WorkTime"></label>
				<input asp-for="WorkTime" class="form-control" placeholder="WorkTime" >
				<span asp-validation-for="WorkTime" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Social">Social</label>
				<input asp-for="Social" class="form-control" placeholder="Social">
				<span asp-validation-for="Social" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Location">Location</label>
				<input asp-for="Location" class="form-control" placeholder="Location">
				<span asp-validation-for="Location" class="text-danger"></span>
			</div>
			<button type="submit" class="btn btn-primary mr-2">Create</button>
		</form>
	</div>
</div>

@section Scripts{
<partial name="_Validation" />
    }

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/AvailableJobs/Delete.cshtml
@model AvailableJob
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/AvailableJobs/Detail.cshtml
@model AvailableJob
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<h1>@Model.Title</h1>
<br />
<h3>WorkTime:   @Model.WorkTime</h3>
<h5>Social:   @Model.Social</h5>
<p>Location:   @Model.Location</p>
<a class="btn btn-dark" asp-controller="availablejobs" asp-action="index">Back</a>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/AvailableJobs/Index.cshtml
@model Pagination<AvailableJob>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
     int count = (Model.CurrentPage - 1) * 5;
}

 <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Available Jobs Table</h4>
                  <a class="btn btn-success" asp-controller="availablejobs" asp-action="Create" >Create</a>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>№</th>
                          <th>Title</th>
                          <th>WorkTime</th>
                          <th>Social</th>
                          <th>Location</th>
                          <th>Setting</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach (var item in Model.Items)
                       {
                                count++;
                         <tr>
                              <td>@count</td>
                              <td>@item.Title</td>
                              <td>@item.WorkTime</td>
                               <td>@item.Social</td>
                              <td>@item.Location</td>
                              <td>
                                  <a class="btn btn-danger" asp-controller="AvailableJobs" asp-action="delete" asp-route-id="@item.Id"><i class="mdi mdi-delete"></i></a>
                                  <a class="btn btn-primary" asp-controller="AvailableJobs" asp-action="update" asp-route-id="@item.Id"><i class="mdi mdi-table-edit"></i></a>
                                  <a class="btn btn-info" asp-controller="AvailableJobs" asp-action="detail" asp-route-id="@item.Id"><i class="mdi mdi-account-card-details"></i></a>
                              </td>
                        </tr>
                       }
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
 </div>

 <div class="row justify-content-center">
	<ul class="pagination pagination-lg">
		@for (var i = 1; i <= Model.PageCount; i++)
		{
			<li class="page-item @(Model.CurrentPage==i? "disabled" : "") ">
				<a class="page-link" 
				asp-area="adminf" 
				asp-controller="AvailableJobs" 
				asp-action="index" 
				asp-route-pageSize="@i">@i</a>
			</li>
		}
	</ul>
</div>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/AvailableJobs/Update.cshtml
@model AvailableJob
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <div class="row">
        <form class="forms-sample" method="post" enctype="multipart/form-data">
                    
                    <div class="form-group">
                      <label asp-for="Title">Name</label>
                      <input asp-for="Title" class="form-control" placeholder="Name">
                      <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="WorkTime">Name</label>
                      <input asp-for="WorkTime" class="form-control" placeholder="WorkTime">
                      <span asp-validation-for="WorkTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                      <label asp-for="Social">Name</label>
                      <input asp-for="Social" class="form-control" placeholder="Social">
                      <span asp-validation-for="Social" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="Location">Location</label>
                      <input asp-for="Location" class="form-control" placeholder="Location">
                      <span asp-validation-for="Location" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Create</button>
                  </form>
    </div>
</div>

@section Scripts{
    <partial name="_Validation"/>
    }