Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Controllers/CandidatesSliderController.cs
using Jobbply__Final_Project.DAL;
using Jobbply__Final_Project.Helpers;
using Jobbply__Final_Project.Models;
using Jobbply__Final_Project.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Jobbply__Final_Project.Areas.AdminF.Controllers
{
    [Area("AdminF")]
    public class CandidatesSliderController : Controller
    {
        private AppDbContext _context;
        private IWebHostEnvironment _env;
        public CandidatesSliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index(int take = 5, int pageSize = 1)
        {
            List<Candidates> candidates = _context.Candidates
                .Skip((pageSize - 1) * take)
                .Take(take)
                .ToList();

            Pagination<Candidates> pagination = new Pagination<Candidates>(
                ReturnPageCount(take),
                pageSize,
                candidates
                );
            return View(pagination);
        }
        private int ReturnPageCount(int take)
        {
            int candidatesCount = _context.Candidates.Count();
            return (int)Math.Ceiling(((decimal)candidatesCount / take));
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return NotFound();

            Candidates dbCandidates = await _context.Candidates.FindAsync(id);
            if (dbCandidates == null) return NotFound();
            return View(dbCandidates);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            Candidates dbCandidates = await _context.Candidates.FindAsync(id);
            if (dbCandidates == null) return NotFound();

            Helper.DeleteFile(_env, "assets", "image", "home", dbCandidates.Image);
            _context.Candidates.Remove(dbCandidates);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Candidates candidates)
        {
            if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                return View();
            }

            if (!candidates.Photo.ContentType.Contains("image"))
            {
                ModelState.AddModelError("Photo", "Accept Only image");
                return View();
            }

            if (candidates.Photo.Length / 1024 > 1024)
            {
                ModelState.AddModelError("Photo", "1mb-dan yuxari ola bilmez");
                return View();
            }
            // string path = @"C:\Users\nargi\Desktop\Jobbply- Final Project\Jobbply- Final Project\wwwroot\assets\image\home\";

            string path = _env.WebRootPath;
            string fileName = Guid.NewGuid().ToString() + candidates.Photo.FileName;
            string result = Path.Combine(path, "assets", "image", "home", fileName);

            using (FileStream stream = new FileStream(result, FileMode.Create))
            {
                await candidates.Photo.CopyToAsync(stream);
            };
            Candidates newCandidates = new Candidates();
            newCandidates.Image = fileName;
            newCandidates.Title = candidates.Title;
            newCandidates.Subtitle = candidates.Subtitle;
            await _context.Candidates.AddAsync(newCandidates);
            await _context.SaveChangesAsync();

            //bool isExistName = _context.ClientSliders.Any(c => c.Name.ToLower() == clientSlider.Name.ToLower());
            //if (isExistName)
            //{
            //    ModelState.AddModelError("Name", "Eyni adli Client movcuddur");
            //    return View();
            //}

            return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return NotFound();

            Candidates dbCandidates = await _context.Candidates.FindAsync(id);
            if (dbCandidates == null) return NotFound();
            return View(dbCandidates);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int? id, Candidates candidates)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            Candidates dbCandidates = await _context.Candidates.FindAsync(id);

            Candidates existNameCandidates = _context.Candidates.FirstOrDefault(c => c.Title.ToLower() == candidates.Title.ToLower());

            if (existNameCandidates != null)
            {
                if (dbCandidates != existNameCandidates)
                {
                    ModelState.AddModelError("Title", "Title already exist");
                }
            }
            string path = _env.WebRootPath;
            string fileName = Guid.NewGuid().ToString() + candidates.Photo.FileName;
            string result = Path.Combine(path, "assets", "image", "home", fileName);

            using (FileStream stream = new FileStream(result, FileMode.Create))
            {
                await candidates.Photo.CopyToAsync(stream);
            };

            if (dbCandidates == null) return NotFound();
            dbCandidates.Image = fileName;
            dbCandidates.Title = candidates.Title;
            dbCandidates.Subtitle = candidates.Subtitle;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/CandidatesSlider/Create.cshtml
@model Candidates
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group" >
                      <label asp-for="Photo"></label>
                      <input asp-for="Photo" class="form-control"  placeholder="Photo" accept="image/*">
                      <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                      <label asp-for="Title">Name</label>
                      <input asp-for="Title" class="form-control" placeholder="Name">
                      <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="Subtitle">Location</label>
                      <input asp-for="Subtitle" class="form-control" placeholder="Location">
                      <span asp-validation-for="Subtitle" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Create</button>
                  </form>
    </div>
</div>

@section Scripts{
    <partial name="_Validation"/>
    }

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/CandidatesSlider/Delete.cshtml
@model Candidates
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/CandidatesSlider/Detail.cshtml
@model Candidates
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<h2>@Model.Title</h2>
<p>@Model.Subtitle</p>
<a class="btn btn-dark" asp-controller="candidates" asp-action="index">Back</a>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/CandidatesSlider/Index.cshtml
@model Pagination<Candidates>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
     int count = (Model.CurrentPage - 1) * 5;
}

 <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Canditate Slider Table</h4>
                  <a class="btn btn-success" asp-controller="candidatesslider" asp-action="Create" >Create</a>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Count</th>
                          <th>Image</th>
                          <th>Title</th>
                          <th>Subtitle</th>
                          <th>Setting</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach (var item in Model.Items)
                       {
                                count++;
                         <tr>
                              <td>@count</td>
                              <td>
                                  <img src="~/assets/image/home/@item.Image" />
                              </td>
                              <td>@item.Title</td>
                              <td>@item.Subtitle</td>
                              <td>
                                  <a class="btn btn-danger" asp-controller="CandidatesSlider" asp-action="delete" asp-route-id="@item.Id"><i class="mdi mdi-delete"></i></a>
                                  <a class="btn btn-primary" asp-controller="CandidatesSlider" asp-action="update" asp-route-id="@item.Id"><i class="mdi mdi-table-edit"></i></a>
                                  <a class="btn btn-info" asp-controller="CandidatesSlider" asp-action="detail" asp-route-id="@item.Id"><i class="mdi mdi-account-card-details"></i></a>
                              </td>
                        </tr>
                       }
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
 </div>

 <div class="row justify-content-center">
	<ul class="pagination pagination-lg">
		@for (var i = 1; i <= Model.PageCount; i++)
		{
			<li class="page-item @(Model.CurrentPage==i? "disabled" : "") ">
				<a class="page-link" 
				asp-area="adminf" 
				asp-controller="candidatesslider" 
				asp-action="index" 
				asp-route-pageSize="@i">@i</a>
			</li>
		}
	</ul>
</div>

Jobbply- Final Project/Jobbply- Final Project/Areas/AdminF/Views/CandidatesSlider/Update.cshtml
@model Candidates
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group" >
                      <label asp-for="Photo"></label>
                      <input asp-for="Photo" class="form-control"  placeholder="Photo" accept="image/*">
                      <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                      <label asp-for="Title">Name</label>
                      <input asp-for="Title" class="form-control" placeholder="Name">
                      <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                     <div class="form-group">
                      <label asp-for="Subtitle">Location</label>
                      <input asp-for="Subtitle" class="form-control" placeholder="Location">
                      <span asp-validation-for="Subtitle" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Create</button>
                  </form>
    </div>
</div>

@section Scripts{
    <partial name="_Validation"/>
    }